# Generated by Django 5.2.9 on 2026-01-06 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_id', models.CharField(max_length=128)),
                ('entity_identifier', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instant_date', models.DateField(blank=True, null=True)),
                ('period_type', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['context_id'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(blank=True, max_length=128)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('instant_date', models.DateField(blank=True, null=True)),
                ('context_reference', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=128)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('xbrl_file', models.FileField(upload_to='xbrl/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='reports.company')),
            ],
            options={
                'ordering': ['-period_end', '-instant_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('namespace', models.CharField(blank=True, max_length=255)),
                ('value', models.TextField(blank=True)),
                ('decimals', models.CharField(blank=True, max_length=32)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='reports.context')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='reports.filing')),
            ],
            options={
                'ordering': ['name', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='context',
            name='filing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='reports.filing'),
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('primary_fact', models.CharField(max_length=255)),
                ('fallback_facts', models.TextField(blank=True, help_text='Masukkan 1 kode item per baris sebagai fallback bila primary kosong.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='filing',
            constraint=models.UniqueConstraint(fields=('company', 'period_label'), name='unique_company_period_label'),
        ),
        migrations.AddConstraint(
            model_name='context',
            constraint=models.UniqueConstraint(fields=('filing', 'context_id'), name='unique_context_per_filing'),
        ),
    ]
