# Generated by Django 5.2.9 on 2026-01-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_company_entity_code_company_entity_main_industry_and_more'),
        ('reports', '0002_laba_rugi_template'),
    ]

    operations = [
    ]
