from django.db import migrations


def create_arus_kas_template(apps, schema_editor):
    ReportTemplate = apps.get_model("reports", "ReportTemplate")
    TemplateItem = apps.get_model("reports", "TemplateItem")

    template, _ = ReportTemplate.objects.get_or_create(
        slug="arus-kas",
        defaults={
            "name": "Laporan Arus Kas",
            "description": "Template laporan arus kas.",
        },
    )

    items = [
        ("Laporan arus kas", "Statementofcashflows"),
        ("Arus kas dari aktivitas operasi", "Cashflowsfromoperatingactivities"),
        ("Penerimaan kas dari aktivitas operasi", "Cashreceiptsfromoperatingactivities"),
        ("Penerimaan dari pelanggan", "Receiptsfromcustomers"),
        (
            "Penerimaan dari penjualan/penurunan modal atas investasi pada saham dan efek ekuitas lainnya",
            "Proceedfromsales/capitaldeductionofinvestmentsinsharesandotherequity",
        ),
        ("Penerimaan subsidi", "Receiptsofsubsidy"),
        (
            "Penerimaan dari royalti, fees, komisi, dan pendapatan lain",
            "Receiptsfromroyalties,fees,commissionsandotherrevenues",
        ),
        (
            "Penerimaan dari kontrak yang dimiliki untuk tujuan diperdagangkan atau diperjualbelikan",
            "Receiptsfromcontractheld-for-dealingortradingpurposes",
        ),
        ("Penerimaan dari perusahaan efek", "Receiptsfromsecuritiescompany"),
        ("Penerimaan kas lainnya dari aktivitas operasi", "Othercashreceiptsfromoperatingactivities"),
        ("Pembayaran kas dari aktivitas operasi", "Cashpaymentsfromoperatingactivities"),
        ("Pembayaran kepada pemasok atas barang dan jasa", "Paymentstosuppliersforgoodsandservices"),
        ("Pembayaran gaji dan tunjangan", "Paymentsforsalariesandallowances"),
        ("Pembayaran beban umum dan administrasi", "Paymentsforgeneralandadministrativeexpense"),
        ("Pembayaran royalti dan iuran eksploitasi", "Paymentsforroyaltiesandexploitationfees"),
        ("Pembayaran kepada kontraktor", "Paymentstocontractors"),
        ("Pembayaran jasa manajemen", "Paymentsformanagementfees"),
        ("Pembayaran kas lainnya untuk beban operasi", "Othercashpaymentsforoperatingactivities"),
        (
            "Pembayaran dari kontrak yang dimiliki untuk tujuan diperdagangkan atau diperjualbelikan",
            "Paymentsfromcontractheld-for-dealingortradingpurposes",
        ),
        ("Kas diperoleh dari (digunakan untuk) operasi", "Cashgeneratedfrom(usedin)operations"),
        (
            "Penerimaan bunga, hasil investasi, provisi, dan komisi",
            "Interest,investmentincome,feesandcommissionsreceived",
        ),
        (
            "Pembayaran bunga dan bonus, provisi dan komisi",
            "PaymentsOfInterestAndBonusFeesAndCommissions",
        ),
        (
            "Penerimaan dari penyertaan saham dalam klasifikasi biaya perolehan diamortisasi dan nilai wajar melalui pendapatan komprehensif lainnya",
            "Proceedsfromequityinvestmentsclassifiedasamortizedcostandfairvaluethroughothercomprehensiveincome",
        ),
        ("Penerimaan dari penjualan atas investasi pada efek", "Proceedsfromsalesofinvestmentinsecurities"),
        ("Penempatan investasi pada efek", "Purchasesofinvestmentinsecurities"),
        ("Penerimaan dividen dari aktivitas operasi", "Dividendsreceivedfromoperatingactivities"),
        ("Pembayaran dividen dari aktivitas operasi", "Dividendspaidfromoperatingactivities"),
        ("Penerimaan bunga dari aktivitas operasi", "Interestsreceivedfromoperatingactivities"),
        ("Pembayaran bunga dari aktivitas operasi", "Interestspaidfromoperatingactivities"),
        ("Penerimaan pengembalian (pembayaran) pajak penghasilan dari aktivitas operasi", "Incometaxesrefunded(paid)fromoperatingactivities"),
        ("Pembayaran utang cukai", "Paymentsforexcisepayable"),
        ("Pengembalian (penempatan) uang jaminan", "Repayment(placement)ofrefundabledeposits"),
        ("Pembayaran pajak penghasilan badan", "Paymentsforcorporateincometax"),
        ("Penerimaan (pengeluaran) kas lainnya dari aktivitas operasi", "Othercashinflows(outflows)fromoperatingactivities"),
        (
            "Arus kas sebelum perubahan dalam aset dan liabilitas yang diperoleh dari (digunakan untuk) aktivitas operasi",
            "Netcashflowsreceivedfrom(usedin)operatingactivitiesbeforechangesinassetsandliabilities",
        ),
        ("Penurunan (kenaikan) aset operasi", "Decrease(increase)fromoperationassets"),
        ("Penurunan (kenaikan) efek-efek", "Decrease(increase)fromsecurities"),
        ("Penurunan (kenaikan) kredit", "Decrease(increase)fromcredit"),
        ("Penurunan (kenaikan) aset lainnya", "Decrease(increase)fromotherassets"),
        ("Kenaikan (penurunan) liabilitas", "Increase(decrease)fromliabilities"),
        ("Kenaikan (penurunan) simpanan dan simpanan dari bank lain", "Increase(decrease)fromdepositsanddepositsfromotherbanks"),
        ("Kenaikan (penurunan) liabilitas lainnya", "Increase(decrease)fromotherliabilities"),
        ("Jumlah arus kas bersih yang diperoleh dari (digunakan untuk) aktivitas operasi", "Totalnetcashflowsreceivedfrom(usedin)operatingactivities"),
        ("Arus kas dari aktivitas investasi", "Cashflowsfrominvestingactivities"),
        ("Pembayaran biaya pengupasan tanah ditangguhkan", "Paymentsfordeferredstrippingcosts"),
        ("Pembayaran biaya mobilisasi ditangguhkan", "Paymentsfordeferredmobilisationcosts"),
        ("Pembayaran biaya ditangguhkan", "Paymentsfordeferredcharges"),
        ("Penerimaan dari (pengeluaran untuk) dana pemeliharaan pesawat", "Receiptsfrom(paymentsfor)aircraftmaintenancefunds"),
        ("Pembayaran uang muka pembelian aset tetap", "Paymentsforadvancesforpurchaseofproperty,plantandequipment"),
        ("Penerimaan dari penjualan persediaan hewan ternak produksi", "Proceedsfromdisposaloflivestockproduction"),
        ("Pembayaran untuk perolehan persediaan hewan ternak produksi", "Paymentsforacquisitionoflivestockproduction"),
        ("Penerimaan dari penjualan hutan tanaman industri", "Proceedsfromdisposalofindustrialtimberplantations"),
        ("Pembayaran untuk perolehan hutan tanaman industri", "Paymentsforacquisitionofindustrialtimberplantations"),
        ("Penerimaan dari penjualan tanaman perkebunan", "Proceedsfromdisposalofplantationassets"),
        ("Pembayaran untuk perolehan tanaman perkebunan", "Paymentsforacquisitionofplantationassets"),
        ("Penerimaan dari penjualan perkebunan plasma", "Proceedsfromdisposalofplasmaplantations"),
        ("Pembayaran untuk perolehan perkebunan plasma", "Paymentsforacquisitionofplasmaplantations"),
        ("Penerimaan dari penjualan properti investasi", "Proceedsfromdisposalofinvestmentproperties"),
        ("Pembayaran untuk perolehan properti investasi", "Paymentsforacquisitionofinvestmentproperties"),
        ("Penerimaan dari penjualan aset tetap", "Proceedsfromdisposalofproperty,plantandequipment"),
        ("Pembayaran untuk perolehan aset tetap", "Paymentsforacquisitionofproperty,plantandequipment"),
        ("Penerimaan dari penjualan aset agunan yang diambil alih", "Proceedsfromdisposalofforeclosedassets"),
        ("Penerimaan dari penjualan aset minyak dan gas bumi", "Proceedsfromdisposalofoilandgasassets"),
        ("Pembayaran untuk perolehan aset minyak dan gas bumi", "Paymentsforacquisitionofoilandgasassets"),
        ("Penerimaan dari penjualan aset eksplorasi dan evaluasi", "Proceedsfromdisposalofexplorationandevaluationassets"),
        ("Pembayaran untuk perolehan aset eksplorasi dan evaluasi", "Paymentsforacquisitionofexplorationandevaluationassets"),
        ("Penerimaan dari penjualan hak penguasaan jalan tol", "Proceedsfromdisposaloftollroadconcessionrights"),
        ("Pembayaran untuk perolehan hak penguasaan jalan tol", "Paymentsforacquisitionoftollroadconcessionrights"),
        ("Penerimaan dari penjualan properti pertambangan", "Proceedsfromdisposalofminingproperties"),
        ("Pembayaran untuk perolehan properti pertambangan", "Paymentsforacquisitionofminingproperties"),
        ("Penerimaan dari penjualan aset takberwujud", "Proceedsfromdisposalofintangibleassets"),
        ("Pembayaran untuk perolehan aset takberwujud", "Paymentsforacquisitionofintangibleassets"),
        ("Penerimaan dari penjualan tanah dalam pengembangan", "Proceedsfromdisposaloflandfordevelopment"),
        ("Pembayaran untuk perolehan tanah dalam pengembangan", "Paymentsforacquisitionoflandfordevelopment"),
        ("Penerimaan dari penjualan aset non-keuangan lainnya", "Proceedsfromdisposalofothernon-financialassets"),
        ("Pembayaran untuk perolehan aset non-keuangan lainnya", "Paymentsforacquisitionofothernon-financialassets"),
        ("Pencairan (penempatan) investasi jangka pendek", "Withdrawal(placement)ofshort-terminvestments"),
        ("Pencairan (penempatan) aset keuangan yang diukur pada nilai wajar melalui laba rugi", "Withdrawal(placement)offinancialassetsatfairvaluethroughprofitorloss"),
        ("Pencairan (penempatan) aset keuangan nilai wajar melalui pendapatan komprehensif lainnya", "Withdrawal(placement)offinancialassetsfairvaluethroughothercomprehensiveincome"),
        ("Pencairan (penempatan) dana yang dibatasi penggunaannya dari aktivitas investasi", "Withdrawal(placement)ofrestrictedfundsfrominvestingactivities"),
        ("Pencairan (penempatan) obligasi dan (atau) sukuk", "Withdrawal(placement)ofbondsand(or)sukuk"),
        ("Penempatan aset keuangan biaya perolehan diamortisasi", "Placementoffinancialassetsamotizedcostinvestments"),
        ("Pencairan aset keuangan biaya perolehan diamortisasi", "Withdrawaloffinancialassetsamortizedcostinvestments"),
        ("Penerimaan dari penjualan aset keuangan", "Proceedsonsaleoffinancialassets"),
        ("Pembayaran untuk perolehan aset keuangan", "Paymentstoacquirefinancialassets"),
        ("Penerimaan dari future contracts, forward contracts, option contracts, dan swap contracts", "Receiptsfromfuturecontracts,forwardcontracts,optioncontractsandswapcontracts"),
        ("Pembayaran untuk future contracts, forward contracts, option contracts, dan swap contracts", "Paymentsforfuturecontracts,forwardcontracts,optioncontractsandswapcontracts"),
        ("Pembayaran uang muka investasi", "Paymentsforadvancesoninvestments"),
        ("Penerimaan pembayaran piutang dari pihak berelasi", "Receiptsfromreceivablesfromrelatedparties"),
        ("Pembayaran pemberian piutang kepada pihak berelasi", "Paymentsofreceivablesfromrelatedparties"),
        ("Penerimaan pembayaran piutang dari pemegang saham", "Receiptsfromreceivablesfromstockholders"),
        ("Pembayaran pemberian piutang kepada pemegang saham", "Paymentsofreceivablesfromstockholders"),
        ("Uang muka dan pinjaman diberikan kepada pihak lain, selain institusi keuangan", "Cashadvancesandloansmadetootherparties,otherthanfinancinginstitutions"),
        ("Penerimaan pengembalian uang muka dan pinjaman diberikan kepada pihak lain", "Cashreceiptsfromtherepaymentofadvancesandloansmadetootherparties"),
        ("Penerimaan dari pelepasan entitas anak", "Proceedsfromdisposalofsubsidiaries"),
        ("Pembayaran untuk perolehan entitas anak", "Paymentsforacquisitionofsubsidiaries"),
        ("Penerimaan dari pelepasan kepentingan di entitas anak tanpa hilangnya pengendalian dari kegiatan investasi", "Proceedsfromsalesofinterestsinsubsidiarieswithoutlossofcontrolfrominvestingactivities"),
        ("Pembayaran untuk perolehan tambahan kepemilikan pada entitas anak", "Paymentsforacquisitionofadditionalinterestsinsubsidiaries"),
        ("Penerimaan dari pelepasan kepemilikan pada entitas ventura bersama", "Proceedsfromsalesofinterestsinjointventures"),
        ("Pembayaran untuk perolehan kepemilikan pada entitas ventura bersama", "Paymentsforacquisitionofinterestsinjointventures"),
        ("Penerimaan dari pelepasan kepemilikan pada entitas asosiasi", "Proceedsfromsalesofinterestsinassociates"),
        ("Pembayaran untuk perolehan kepemilikan pada entitas asosiasi", "Paymentsforacquisitionofinterestsinassociates"),
        ("Penerimaan dari pelepasan aset tidak lancar atau kelompok lepasan yang diklasifikasikan sebagai dimiliki untuk dijual dan operasi yang dihentikan", "Proceedsfromdisposalofnon-currentassetsordisposalgroupsclassifiedasheld-for-saleanddiscontinuedoperations"),
        ("Penerimaan dividen dari aktivitas investasi", "Dividendsreceivedfrominvestingactivities"),
        ("Penerimaan bunga dari aktivitas investasi", "Interestsreceivedfrominvestingactivities"),
        ("Pembayaran bunga dari aktivitas investasi", "Interestspaidfrominvestingactivities"),
        ("Penerimaan pengembalian (pembayaran) pajak penghasilan dari aktivitas investasi", "Incometaxesrefunded(paid)frominvestingactivities"),
        ("Penerimaan (pengeluaran) kas lainnya dari aktivitas investasi", "Othercashinflows(outflows)frominvestingactivities"),
        ("Jumlah arus kas bersih yang diperoleh dari (digunakan untuk) aktivitas investasi", "Totalnetcashflowsreceivedfrom(usedin)investingactivities"),
        ("Arus kas dari aktivitas pendanaan", "Cashflowsfromfinancingactivities"),
        ("Penerimaan pinjaman bank", "Proceedsfrombankloans"),
        ("Pembayaran pinjaman bank", "Paymentsofbankloans"),
        ("Penerimaan pinjaman dari lembaga keuangan non-bank", "Proceedsfromnon-bankfinancialinstitutionloan"),
        ("Pembayaran pinjaman kepada lembaga keuangan non-bank", "Paymentsofnon-bankfinancialinstitutionloan"),
        ("Penerimaan pinjaman beragunan", "Proceedsfromsecuredloans"),
        ("Pembayaran pinjaman beragunan", "Paymentsofsecuredloans"),
        ("Penerimaan pinjaman tanpa agunan", "Proceedsfromunsecuredloans"),
        ("Pembayaran pinjaman tanpa agunan", "Paymentsofunsecuredloans"),
        ("Penerimaan pinjaman penerusan", "Proceedsfromsteploans"),
        ("Pembayaran pinjaman penerusan", "Paymentsofsteploans"),
        ("Penerimaan utang dari bantuan pemerintah republik Indonesia", "Proceedsfromloanfromgovernmentoftherepublicofindonesia"),
        ("Pembayaran utang bantuan dari pemerintah republik indonesia", "Paymentsofloanfromgovernmentoftherepublicofindonesia"),
        ("Penerimaan pinjaman subordinasi", "Proceedsfromsubordinatedloans"),
        ("Pembayaran pinjaman subordinasi", "Paymentsofsubordinatedloans"),
        ("Penerimaan liabilitas kerjasama operasi", "Proceedsfromjointoperationliabilities"),
        ("Pembayaran liabilitas kerjasama operasi", "Paymentsofjointoperationliabilities"),
        ("Penerimaan utang pembiayaan konsumen", "Proceedsfromconsumerfinancingpayables"),
        ("Pembayaran utang pembiayaan konsumen", "Paymentsofconsumerfinancingpayables"),
        ("Penerimaan liabilitas sewa pembiayaan", "Proceedsfromfinanceleaseliabilities"),
        ("Pembayaran liabilitas sewa pembiayaan", "Paymentsoffinanceleaseliabilities"),
        ("Penerimaan utang listrik swasta", "Proceedsfromelectricitypurchasepayables"),
        ("Pembayaran utang listrik swasta", "Paymentsofelectricitypurchasepayables"),
        ("Penerimaan utang retensi", "Proceedsfromretentionpayables"),
        ("Pembayaran utang retensi", "Paymentsofretentionpayables"),
        ("Penerimaan wesel bayar", "Proceedsfromnotespayable"),
        ("Pembayaran wesel bayar", "Paymentsofnotespayable"),
        ("Penerimaan dari surat utang jangka menengah", "Proceedsfrommediumtermnotes"),
        ("Pembayaran dari surat utang jangka menengah", "Paymentsofmediumtermnotes"),
        ("Penerimaan dari penerbitan obligasi", "Proceedsfrombondspayable"),
        ("Pembayaran utang obligasi", "Paymentsofbondspayable"),
        ("Obligasi subordinasi yang diterbitkan", "Subordinatedbondsissued"),
        ("Pembayaran obligasi subordinasi", "Paymentsofsubordinatedbonds"),
        ("Penerimaan sukuk", "Proceedsfromsukuk"),
        ("Pembayaran sukuk", "Paymentsofsukuk"),
        ("Penerimaan pinjaman lainnya", "Proceedsfromotherborrowings"),
        ("Pembayaran pinjaman lainnya", "Paymentsofotherborrowings"),
        ("Penerimaan dari penerbitan obligasi konversi", "Proceedsfromconvertiblebondsissuance"),
        ("Pembayaran obligasi konversi", "Paymentsofconvertiblebonds"),
        ("Pembayaran biaya emisi penerbitan obligasi", "Paymentsofbondsissuancecosts"),
        ("Pencairan (penempatan) dana yang dibatasi penggunaannya dari aktivitas pendanaan", "Withdrawal(placement)ofrestrictedfundsfromfinancingactivities"),
        ("Penerimaan utang pihak berelasi", "Proceedsfromduetorelatedparties"),
        ("Pembayaran utang pihak berelasi", "Paymentsofduetorelatedparties"),
        ("Penerimaan utang pemegang saham", "Proceedsfromduetostockholders"),
        ("Pembayaran utang pemegang saham", "Paymentsofduetostockholders"),
        ("Penerimaan dari penerbitan saham biasa", "Proceedsfromissuanceofcommonstocks"),
        ("Penerimaan dari penerbitan saham preferen", "Proceedsfromissuanceofpreferredstocks"),
        ("Penerimaan dari penerbitan instrumen ekuitas lainnya", "Proceedsfromissuingotherequityinstruments"),
        ("Pembayaran biaya emisi saham", "Paymentsofstockissuancecosts"),
        ("Penerimaan dari penjualan (pembelian) saham tresuri", "Proceedsfromsales(purchases)oftreasurystocks"),
        ("Penerimaan dari program opsi saham karyawan", "Proceedsfromemployeestockoptionsprogram"),
        ("Penyelesaian (penempatan) transaksi derivatif", "Settlement(placement)ofderivativetransactions"),
        ("Penerimaan dari pelepasan kepentingan di entitas anak tanpa hilangnya pengendalian dari kegiatan pendanaan", "Proceedsfromsalesofinterestsinsubsidiarieswithoutlossofcontrolfromfinancingactivities"),
        ("Penerimaan dari penambahan kepemilikan dari non-pengendali", "Proceedfromincreaseofnon-controllinginterest"),
        ("Pembayaran untuk perolehan kepentingan pihak non-pengendali pada entitas anak", "Paymentsforacquisitionofnon-controllinginterestsinsubsidiaries"),
        ("Pembayaran dividen dari aktivitas pendanaan", "Dividendspaidfromfinancingactivities"),
        ("Penerimaan bunga dari aktivitas pendanaan", "Interestsreceivedfromfinancingactivities"),
        ("Pembayaran bunga dari aktivitas pendanaan", "Interestspaidfromfinancingactivities"),
        ("Penerimaan pengembalian (pembayaran) pajak penghasilan dari aktivitas pendanaan", "Incometaxesrefunded(paid)fromfinancingactivities"),
        ("Penerimaan (pengeluaran) kas lainnya dari aktivitas pendanaan", "Othercashinflows(outflows)fromfinancingactivities"),
        ("Jumlah arus kas bersih yang diperoleh dari (digunakan untuk) aktivitas pendanaan", "Totalnetcashflowsreceivedfrom(usedin)financingactivities"),
        ("Jumlah kenaikan (penurunan) bersih kas dan setara kas", "Totalnetincrease(decrease)incashandcashequivalents"),
        ("Kas dan setara kas arus kas, awal periode", "Cashandcashequivalentscashflows,beginningoftheperiod"),
        ("Efek perubahan nilai kurs pada kas dan setara kas", "Effectofexchangeratechangesoncashandcashequivalents"),
        ("Kas dan setara kas dari entitas anak yang didekonsolidasikan", "Cashandcashequivalentofdeconsolidatedsubsidiaries"),
        ("Kenaikan (penurunan) kas dan setara kas lainnya", "Otherincrease(decrease)incashandcashequivalents"),
        ("Kas dan setara kas arus kas, akhir periode", "Cashandcashequivalentscashflows,endoftheperiod"),
    ]

    for order, (label, primary_fact) in enumerate(items, start=1):
        item, created = TemplateItem.objects.get_or_create(
            template=template,
            label=label,
            defaults={"primary_fact": primary_fact, "order": order},
        )
        if not created:
            updates = {}
            if item.primary_fact != primary_fact:
                updates["primary_fact"] = primary_fact
            if item.order != order:
                updates["order"] = order
            if updates:
                TemplateItem.objects.filter(pk=item.pk).update(**updates)


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_laba_rugi_template"),
    ]

    operations = [
        migrations.RunPython(create_arus_kas_template, migrations.RunPython.noop),
    ]
