# Generated by Django 5.2.9 on 2026-01-07 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_arus_kas_template'),
        ('reports', '0003_merge_20260107_1100'),
    ]

    operations = [
    ]
