# Generated by Django 5.2.9 on 2026-01-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_merge_0003_arus_kas_template_0003_merge_20260107_1100'),
        ('reports', '0004_templateitem_level'),
    ]

    operations = [
    ]
